version: "3.7"

services:
  mariadb:
    image: mariadb:10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=5up€rS€cr€tP4$$w0rd
    volumes:
      - '/media/MariaDbDrive:/var/lib/mysql'
    restart: unless-stopped
  automatedbackup:
    build:
      context: .
    restart: unless-stopped
    environment:
      - "RETENTION_DAYS=15"
      - "DB_HOST=mariadb"
      - "BACKUP_owncloud=5up€rS€cr€tP4$$w0rd
      - "BACKUP_wordpress=5up€rS€cr€tP4$$w0rd
    volumes:
      - "/media/BackupDrive:/backup"
      - "./docker-compose.yml:/custom/docker-compose.yml:ro"
    depends_on:
      - mariadb
